books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_book, name='add_book'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
]

books/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Auteurs'
    
    
class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = "Catégories"
    
class Books(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    quantity = models.PositiveBigIntegerField(default=1)
    published_date = models.DateField()
    isbn = models.CharField(max_length=13, null=True, blank=True)
    
    
    def __str__(self):
        return f"{self.title} ({self.quantity})"
    
    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Livres'

books/forms.py
from django import forms
from books.models import Author, Category, Books

class BookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['title', 'author', 'category', 'quantity', 'published_date', 'isbn']
        widgets = {
            'published_date': forms.DateInput(attrs={'type': 'date'})
        }
        
    def title_clean(self):
        title = self.cleaned_data['title']
        if len(title) < 10:
            raise forms.ValidationError("Le titre doit comporter au moins 10 caractères")
        return title
    
    def isbn_clean(self):
        isbn = self.cleaned_data['isbn']
        if len(isbn) != 13:
            raise forms.ValidationError("L'ISBN doit comporter 13 caractères")
        return isbn
    
    def quantity_clean(self):
        quantity = self.cleaned_data['quantity']
        if quantity < 1:
            raise forms.ValidationError("La quantité doit être supérieure à 0")
        return quantity

books/views.py
from django.shortcuts import render
from books.models import Books
from books.forms import BookForm

def index(request):
    books = Books.objects.filter(quantity__gt=0)
    form = BookForm()
    return render(request, 'books/index.html', {'books': books, 'form': form})


def add_book(request):
    if request.method == 'POST':
        forms = BookForm(request.POST)
        if forms.is_valid():
            forms.save()
    else:
        forms = BookForm()
    return render(request, 'books/index.html', {'form': forms})

books/templates/books/index.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="container-fluid">
    <!-- BreadCrumb -->
    <nav aria-label="breadcrumb" role="navigation">
      <ol class="breadcrumb adminx-page-breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Tableau de bord</li>
      </ol>
    </nav>

    <div class="pb-3">
      <h1>Tableau de bord</h1>
    </div>
    <div class="row">
        <div class="col-md-6 col-lg-3 d-flex">
          <div class="card border-0 bg-primary text-white text-center mb-grid w-100">
            <div class="d-flex flex-row align-items-center h-100">
              <div class="card-icon d-flex align-items-center h-100 justify-content-center">
                <i data-feather="book"></i>
              </div>
              <div class="card-body">
                <div class="card-info-title">Nombre de livres disponible</div>
                <h3 class="card-title mb-0">{{ books.count }}</h3>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex">
          <div class="card border-0 bg-success text-white text-center mb-grid w-100">
            <div class="d-flex flex-row align-items-center h-100">
              <div class="card-icon d-flex align-items-center h-100 justify-content-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              </div>
              <div class="card-body">
                <div class="card-info-title">Inscriptions (cette semaine)</div>
                <h3 class="card-title mb-0">1 258</h3>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Button to Open the Modal -->
      <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#addBookModal">
        Ajouter un livre
      </button>

      <!-- The Modal -->
      <div class="modal" id="addBookModal">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Ajouter un livre</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">
              <form method="post" action="{% url 'books:add_book' %}">
                {% csrf_token %}
                <div class="row w-100">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="title">Titre:</label>
                      {{ form.title|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="author">Auteur:</label>
                      {{ form.author|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="author">Categories:</label>
                      {{ form.category|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="author">Quantiter:</label>
                      {{ form.quantity|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="author">Date de publication: </label>
                      {{ form.published_date|add_class:"form-control" }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="isbn">isbn: </label>
                      {{ form.isbn|add_class:"form-control" }}
                    </div>
                  </div>
                </div>
                <button type="submit" class="btn btn-primary">Ajouter</button>
              </form>
            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
            </div>

          </div>
        </div>
      </div>

      <!-- Table of Available Books -->
      <div class="mt-4 container-lg">
        <h2>Liste des livres disponibles</h2>
        <div class="card mb-grid">
          <div class="card-header d-flex justify-content-between align-items-center">
            <div class="card-header-title">Table</div>
          </div>
          <div class="table-responsive-md">
            <table class="table table-actions table-striped table-hover mb-0">
              <thead>
                <tr>
                  <th scope="col">
                    <label class="custom-control custom-checkbox m-0 p-0">
                      <input type="checkbox" class="custom-control-input table-select-all">
                      <span class="custom-control-indicator"></span>
                    </label>
                  </th>
                  <th scope="col">Nom du livre</th>
                  <th scope="col">Autheur</th>
                  <th scope="col">Quantiter</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for book in books %}
                <tr>
                  <th scope="row">
                    <label class="custom-control custom-checkbox m-0 p-0">
                      <input type="checkbox" class="custom-control-input table-select-row">
                      <span class="custom-control-indicator"></span>
                    </label>
                  </th>
                  <td>{{ book.title }}</td>
                  <td>{{ book.author }}</td>
                  <td>
                    <span class="badge badge-pill badge-primary">{{ book.quantity }}</span>
                  </td>
                  <td>
                    <button class="btn btn-sm btn-primary">Edit</button>
                    <button class="btn btn-sm btn-danger">Delete</button>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
  </div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>AdminX - The last Admin template you'll ever need</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/adminx.css' %}" media="screen" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--
      # Optional Resources
      Feel free to delete these if you don't need them in your project
    -->
  </head>
  <body>
    <div class="adminx-container">
      <nav class="navbar navbar-expand justify-content-between fixed-top">
        <a class="navbar-brand mb-0 h1 d-none d-md-block" href="index.html">
          <img src="{% static 'demo/img/logo.png' %}" class="navbar-brand-image d-inline-block align-top mr-2" alt="">
          Bibliothèque
        </a>

        <div class="d-flex flex-1 d-block d-md-none">
          <a href="#" class="sidebar-toggle ml-3">
            <i data-feather="menu"></i>
          </a>
        </div>

        <ul class="navbar-nav d-flex justify-content-end mr-2">
          <!-- Notificatoins -->
          <li class="nav-item dropdown d-flex align-items-center mr-2">
            <a class="nav-link nav-link-notifications" id="dropdownNotifications" data-toggle="dropdown" href="#">
              <i class="oi oi-bell display-inline-block align-middle"></i>
              <span class="nav-link-notification-number">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-notifications" aria-labelledby="dropdownNotifications">
              <div class="notifications-header d-flex justify-content-between align-items-center">
                <span class="notifications-header-title">
                  Notifications
                </span>
                <a href="#" class="d-flex"><small>Mark all as read</small></a>
              </div>

              <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action unread">
                  <p class="mb-1">Invitation for <strong>Lunch</strong> on <strong>Jan 12th 2018</strong> by <strong>Laura</strong></p>

                  <div class="mb-1">
                    <button type="button" class="btn btn-primary btn-sm">Accept invite</button>
                    <button type="button" class="btn btn-outline-danger btn-sm">Decline</button>
                  </div>

                  <small>1 hour ago</small>
                </a>

                <a href="#" class="list-group-item list-group-item-action">
                  <p class="mb-1"><strong class="text-success">Goal completed</strong><br />1,000 new members today</p>
                  <small>3 days ago</small>
                </a>

                <a href="#" class="list-group-item list-group-item-action">
                  <p class="mb-1 text-danger"><strong>System error detected</strong></p>
                  <small>3 days ago</small>
                </a>

                <a href="#" class="list-group-item list-group-item-action">
                  <p class="mb-1">Your task <strong>Design Draft</strong> is due today.</p>
                  <small>4 days ago</small>
                </a>
              </div>

              <div class="notifications-footer text-center">
                <a href="#"><small>View all notifications</small></a>
              </div>
            </div>
          </li>
          <!-- Notifications -->
          <li class="nav-item dropdown">
            <a class="nav-link avatar-with-name" id="navbarDropdownMenuLink" data-toggle="dropdown" href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jsa/128.jpg" class="d-inline-block align-top" alt="">
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">My Profile</a>
              <a class="dropdown-item" href="#">My Tasks</a>
              <a class="dropdown-item" href="#">Settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-danger" href="#">Sign out</a>
            </div>
          </li>
        </ul>
      </nav>

      <!-- expand-hover push -->
      <!-- Sidebar -->
    <div class="adminx-sidebar expand-hover push">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-item">
        <a href="" class="sidebar-nav-link active">
          <span class="sidebar-nav-icon">
            <i data-feather="home"></i>
          </span>
          <span class="sidebar-nav-name">
            Accueil
          </span>
        </a>
        </li>

        <li class="sidebar-nav-item">
        <a href="" class="sidebar-nav-link">
          <span class="sidebar-nav-icon">
            <i data-feather="book"></i>
          </span>
          <span class="sidebar-nav-name">
            Livres
          </span>
        </a>
        </li>

        <li class="sidebar-nav-item">
        <a href="" class="sidebar-nav-link">
          <span class="sidebar-nav-icon">
            <i data-feather="user"></i>
          </span>
          <span class="sidebar-nav-name">
            Auteurs
          </span>
        </a>
        </li>

        <li class="sidebar-nav-item">
        <a href="" class="sidebar-nav-link">
          <span class="sidebar-nav-icon">
            <i data-feather="tag"></i>
          </span>
          <span class="sidebar-nav-name">
            Catégories
          </span>
        </a>
        </li>

        <li class="sidebar-nav-item">
        <a href="" class="sidebar-nav-link">
          <span class="sidebar-nav-icon">
            <i data-feather="settings"></i>
          </span>
          <span class="sidebar-nav-name">
            Profil
          </span>
        </a>
        </li>
      </ul>
    </div><!-- Sidebar End -->

      <!-- adminx-content-aside -->
      <div class="adminx-content">
        <!-- <div class="adminx-aside">

        </div> -->

        <div class="adminx-main-content">
            {% block content %}{% endblock content %}
        </div>
      </div>
    </div>

    <!-- If you prefer jQuery these are the required scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="{% static 'dist/js/vendor.js' %}"></script>
    <script src="{% static 'dist/js/adminx.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>

    <!-- If you prefer vanilla JS these are the only required scripts -->
    <!-- script src="./dist/js/vendor.js"></script>
    <script src="./dist/js/adminx.vanilla.js"></script-->
      <script>
        flatpickr("#datepicker", {
          altInput: true,
          dateFormat: "d-m-Y",
      });
      </script>
  </body>
</html>